import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import type { LocalItem } from "@/app/api/cron/local-events/route";

// "Around Town" card data. Reads the latest weekly snapshot generated by the
// local-events cron; never triggers a generation itself.
export const revalidate = 3600; // 1 hour

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export async function GET() {
  try {
    const { data } = await supabase
      .from("mirror_local_events")
      .select("week_start, generated_at, items")
      .order("week_start", { ascending: false })
      .limit(1)
      .maybeSingle();

    if (!data) return NextResponse.json({ items: [] });

    // A weekly snapshot older than 9 days means the cron is failing; better
    // to show nothing than stale listings.
    const ageMs = Date.now() - new Date(data.generated_at).getTime();
    if (ageMs > 9 * 86_400_000) return NextResponse.json({ items: [] });

    const today = new Date().toISOString().slice(0, 10);
    const items = (data.items as LocalItem[]).filter(
      (it) => it.kind === "special" || (it.date !== null && it.date >= today)
    );

    return NextResponse.json({ items, weekStart: data.week_start });
  } catch {
    return NextResponse.json({ items: [] });
  }
}
